import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import Image from "next/image";
import Providers from "@/lib/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const backgroundStyles = {
  backgroundImage: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(/Kyle-de-Nobrega-Gabon-Loango-22-of-81-2.jpg)`,
  backgroundSize: 'cover',
  backgroundPosition: 'center'
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="flex min-h-svh flex-col items-center justify-center gap-6 bg-muted p-6 md:p-10" style={backgroundStyles}>
            <div className="flex w-full max-w-sm flex-col gap-6">
              <div className="bg-white flex justify-center gap-2 items-center p-3 rounded-md">
                <Image src={'/Flag_of_Gabon.svg.webp'} alt="Gabon's flag" width={30} height={30} className="w-10" />
                <span className="font-bold text-4xl">ParkPro</span>
              </div>
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
